# Site settings
title: Sajad Ayooby Full-stack Developer
header: I am Back-End Developer in Love with Laravel
email: sajad.hi@gmail.com
url: http://localhost:4000/ayooby.github.io/
description: "laravel back-end Developer and php Developing, i love to learn new Tech and more than that i love help to other pepole,"
skills: "Back-End Developer - Front-End Developer - Android..."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1FA4B6 #80B3FF this is disable because we need to use transparency
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 1FBBA6 #FD6E8A
  secondary-dark: 1FA4B6 #A2122F

# Footer settings
footer:
  copyright: All is Free
  location: Lara What!
  social: Find Me 
  credits: Free hosting with GitHub Pages

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sajad666
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/sajad-ayooby

# Postal address (add as many lines as necessary)
address:
  - line: Laravel is a free open-source 
  - line: PHP web application framework.
  - line: If You Want to Know More You can
  - line: Visit following links':'
  - title: Laravel Offical Webstie
  - url: 'http://laravel.com/'


# Credits content
credits: 'This Webstie is Powered By jekyll and Hosted on GitHub'

# Build settings
markdown: kramdown
permalink: pretty
